// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XMDKNN_H
#define XMDKNN_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmdknn_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Bus_a_BaseAddress;
} XMdknn_Config;
#endif

typedef struct {
    u32 Bus_a_BaseAddress;
    u32 IsReady;
} XMdknn;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMdknn_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMdknn_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMdknn_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMdknn_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMdknn_Initialize(XMdknn *InstancePtr, u16 DeviceId);
XMdknn_Config* XMdknn_LookupConfig(u16 DeviceId);
int XMdknn_CfgInitialize(XMdknn *InstancePtr, XMdknn_Config *ConfigPtr);
#else
int XMdknn_Initialize(XMdknn *InstancePtr, const char* InstanceName);
int XMdknn_Release(XMdknn *InstancePtr);
#endif

void XMdknn_Start(XMdknn *InstancePtr);
u32 XMdknn_IsDone(XMdknn *InstancePtr);
u32 XMdknn_IsIdle(XMdknn *InstancePtr);
u32 XMdknn_IsReady(XMdknn *InstancePtr);
void XMdknn_EnableAutoRestart(XMdknn *InstancePtr);
void XMdknn_DisableAutoRestart(XMdknn *InstancePtr);


void XMdknn_InterruptGlobalEnable(XMdknn *InstancePtr);
void XMdknn_InterruptGlobalDisable(XMdknn *InstancePtr);
void XMdknn_InterruptEnable(XMdknn *InstancePtr, u32 Mask);
void XMdknn_InterruptDisable(XMdknn *InstancePtr, u32 Mask);
void XMdknn_InterruptClear(XMdknn *InstancePtr, u32 Mask);
u32 XMdknn_InterruptGetEnabled(XMdknn *InstancePtr);
u32 XMdknn_InterruptGetStatus(XMdknn *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
