toplevel_dir := $(CURDIR)/../../../

BIN = roundtrip
PL_NAME = roundtrip_v1_0
SRCS = roundtrip.c
BSP_HOME = ../common/bsp

all: zynq

test:
	@echo $(mkfile_path)
	@echo $(current_dir)
	@echo $(toplevel_dir)
	@echo $(CURDIR)

include ../../../common/makefiles/Makefile.arm
