// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XROUNDTRIP_H
#define XROUNDTRIP_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xroundtrip_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Bus_a_BaseAddress;
} XRoundtrip_Config;
#endif

typedef struct {
    u32 Bus_a_BaseAddress;
    u32 IsReady;
} XRoundtrip;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XRoundtrip_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XRoundtrip_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XRoundtrip_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XRoundtrip_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XRoundtrip_Initialize(XRoundtrip *InstancePtr, u16 DeviceId);
XRoundtrip_Config* XRoundtrip_LookupConfig(u16 DeviceId);
int XRoundtrip_CfgInitialize(XRoundtrip *InstancePtr, XRoundtrip_Config *ConfigPtr);
#else
int XRoundtrip_Initialize(XRoundtrip *InstancePtr, const char* InstanceName);
int XRoundtrip_Release(XRoundtrip *InstancePtr);
#endif

void XRoundtrip_Start(XRoundtrip *InstancePtr);
u32 XRoundtrip_IsDone(XRoundtrip *InstancePtr);
u32 XRoundtrip_IsIdle(XRoundtrip *InstancePtr);
u32 XRoundtrip_IsReady(XRoundtrip *InstancePtr);
void XRoundtrip_EnableAutoRestart(XRoundtrip *InstancePtr);
void XRoundtrip_DisableAutoRestart(XRoundtrip *InstancePtr);
u32 XRoundtrip_Get_return(XRoundtrip *InstancePtr);


void XRoundtrip_InterruptGlobalEnable(XRoundtrip *InstancePtr);
void XRoundtrip_InterruptGlobalDisable(XRoundtrip *InstancePtr);
void XRoundtrip_InterruptEnable(XRoundtrip *InstancePtr, u32 Mask);
void XRoundtrip_InterruptDisable(XRoundtrip *InstancePtr, u32 Mask);
void XRoundtrip_InterruptClear(XRoundtrip *InstancePtr, u32 Mask);
u32 XRoundtrip_InterruptGetEnabled(XRoundtrip *InstancePtr);
u32 XRoundtrip_InterruptGetStatus(XRoundtrip *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
