// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmergesort.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMergesort_CfgInitialize(XMergesort *InstancePtr, XMergesort_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_a_BaseAddress = ConfigPtr->Bus_a_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMergesort_Start(XMergesort *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMergesort_ReadReg(InstancePtr->Bus_a_BaseAddress, XMERGESORT_BUS_A_ADDR_AP_CTRL) & 0x80;
    XMergesort_WriteReg(InstancePtr->Bus_a_BaseAddress, XMERGESORT_BUS_A_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMergesort_IsDone(XMergesort *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMergesort_ReadReg(InstancePtr->Bus_a_BaseAddress, XMERGESORT_BUS_A_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMergesort_IsIdle(XMergesort *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMergesort_ReadReg(InstancePtr->Bus_a_BaseAddress, XMERGESORT_BUS_A_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMergesort_IsReady(XMergesort *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMergesort_ReadReg(InstancePtr->Bus_a_BaseAddress, XMERGESORT_BUS_A_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMergesort_EnableAutoRestart(XMergesort *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMergesort_WriteReg(InstancePtr->Bus_a_BaseAddress, XMERGESORT_BUS_A_ADDR_AP_CTRL, 0x80);
}

void XMergesort_DisableAutoRestart(XMergesort *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMergesort_WriteReg(InstancePtr->Bus_a_BaseAddress, XMERGESORT_BUS_A_ADDR_AP_CTRL, 0);
}

void XMergesort_InterruptGlobalEnable(XMergesort *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMergesort_WriteReg(InstancePtr->Bus_a_BaseAddress, XMERGESORT_BUS_A_ADDR_GIE, 1);
}

void XMergesort_InterruptGlobalDisable(XMergesort *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMergesort_WriteReg(InstancePtr->Bus_a_BaseAddress, XMERGESORT_BUS_A_ADDR_GIE, 0);
}

void XMergesort_InterruptEnable(XMergesort *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMergesort_ReadReg(InstancePtr->Bus_a_BaseAddress, XMERGESORT_BUS_A_ADDR_IER);
    XMergesort_WriteReg(InstancePtr->Bus_a_BaseAddress, XMERGESORT_BUS_A_ADDR_IER, Register | Mask);
}

void XMergesort_InterruptDisable(XMergesort *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMergesort_ReadReg(InstancePtr->Bus_a_BaseAddress, XMERGESORT_BUS_A_ADDR_IER);
    XMergesort_WriteReg(InstancePtr->Bus_a_BaseAddress, XMERGESORT_BUS_A_ADDR_IER, Register & (~Mask));
}

void XMergesort_InterruptClear(XMergesort *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMergesort_WriteReg(InstancePtr->Bus_a_BaseAddress, XMERGESORT_BUS_A_ADDR_ISR, Mask);
}

u32 XMergesort_InterruptGetEnabled(XMergesort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMergesort_ReadReg(InstancePtr->Bus_a_BaseAddress, XMERGESORT_BUS_A_ADDR_IER);
}

u32 XMergesort_InterruptGetStatus(XMergesort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMergesort_ReadReg(InstancePtr->Bus_a_BaseAddress, XMERGESORT_BUS_A_ADDR_ISR);
}

