// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XKMP_H
#define XKMP_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xkmp_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Bus_a_BaseAddress;
} XKmp_Config;
#endif

typedef struct {
    u32 Bus_a_BaseAddress;
    u32 IsReady;
} XKmp;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XKmp_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XKmp_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XKmp_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XKmp_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XKmp_Initialize(XKmp *InstancePtr, u16 DeviceId);
XKmp_Config* XKmp_LookupConfig(u16 DeviceId);
int XKmp_CfgInitialize(XKmp *InstancePtr, XKmp_Config *ConfigPtr);
#else
int XKmp_Initialize(XKmp *InstancePtr, const char* InstanceName);
int XKmp_Release(XKmp *InstancePtr);
#endif

void XKmp_Start(XKmp *InstancePtr);
u32 XKmp_IsDone(XKmp *InstancePtr);
u32 XKmp_IsIdle(XKmp *InstancePtr);
u32 XKmp_IsReady(XKmp *InstancePtr);
void XKmp_EnableAutoRestart(XKmp *InstancePtr);
void XKmp_DisableAutoRestart(XKmp *InstancePtr);
u32 XKmp_Get_return(XKmp *InstancePtr);


void XKmp_InterruptGlobalEnable(XKmp *InstancePtr);
void XKmp_InterruptGlobalDisable(XKmp *InstancePtr);
void XKmp_InterruptEnable(XKmp *InstancePtr, u32 Mask);
void XKmp_InterruptDisable(XKmp *InstancePtr, u32 Mask);
void XKmp_InterruptClear(XKmp *InstancePtr, u32 Mask);
u32 XKmp_InterruptGetEnabled(XKmp *InstancePtr);
u32 XKmp_InterruptGetStatus(XKmp *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
