// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xbfs_queue.h"

extern XBfs_queue_Config XBfs_queue_ConfigTable[];

XBfs_queue_Config *XBfs_queue_LookupConfig(u16 DeviceId) {
	XBfs_queue_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XBFS_QUEUE_NUM_INSTANCES; Index++) {
		if (XBfs_queue_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XBfs_queue_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XBfs_queue_Initialize(XBfs_queue *InstancePtr, u16 DeviceId) {
	XBfs_queue_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XBfs_queue_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XBfs_queue_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

