// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XBFS_QUEUE_H
#define XBFS_QUEUE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xbfs_queue_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Bus_a_BaseAddress;
} XBfs_queue_Config;
#endif

typedef struct {
    u32 Bus_a_BaseAddress;
    u32 IsReady;
} XBfs_queue;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XBfs_queue_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XBfs_queue_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XBfs_queue_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XBfs_queue_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XBfs_queue_Initialize(XBfs_queue *InstancePtr, u16 DeviceId);
XBfs_queue_Config* XBfs_queue_LookupConfig(u16 DeviceId);
int XBfs_queue_CfgInitialize(XBfs_queue *InstancePtr, XBfs_queue_Config *ConfigPtr);
#else
int XBfs_queue_Initialize(XBfs_queue *InstancePtr, const char* InstanceName);
int XBfs_queue_Release(XBfs_queue *InstancePtr);
#endif

void XBfs_queue_Start(XBfs_queue *InstancePtr);
u32 XBfs_queue_IsDone(XBfs_queue *InstancePtr);
u32 XBfs_queue_IsIdle(XBfs_queue *InstancePtr);
u32 XBfs_queue_IsReady(XBfs_queue *InstancePtr);
void XBfs_queue_EnableAutoRestart(XBfs_queue *InstancePtr);
void XBfs_queue_DisableAutoRestart(XBfs_queue *InstancePtr);


void XBfs_queue_InterruptGlobalEnable(XBfs_queue *InstancePtr);
void XBfs_queue_InterruptGlobalDisable(XBfs_queue *InstancePtr);
void XBfs_queue_InterruptEnable(XBfs_queue *InstancePtr, u32 Mask);
void XBfs_queue_InterruptDisable(XBfs_queue *InstancePtr, u32 Mask);
void XBfs_queue_InterruptClear(XBfs_queue *InstancePtr, u32 Mask);
u32 XBfs_queue_InterruptGetEnabled(XBfs_queue *InstancePtr);
u32 XBfs_queue_InterruptGetStatus(XBfs_queue *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
