// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xmergesort.h"

extern XMergesort_Config XMergesort_ConfigTable[];

XMergesort_Config *XMergesort_LookupConfig(u16 DeviceId) {
	XMergesort_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XMERGESORT_NUM_INSTANCES; Index++) {
		if (XMergesort_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XMergesort_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XMergesort_Initialize(XMergesort *InstancePtr, u16 DeviceId) {
	XMergesort_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XMergesort_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XMergesort_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

