// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xcopy_axi.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XCopy_axi_CfgInitialize(XCopy_axi *InstancePtr, XCopy_axi_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_a_BaseAddress = ConfigPtr->Bus_a_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XCopy_axi_Start(XCopy_axi *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCopy_axi_ReadReg(InstancePtr->Bus_a_BaseAddress, XCOPY_AXI_BUS_A_ADDR_AP_CTRL) & 0x80;
    XCopy_axi_WriteReg(InstancePtr->Bus_a_BaseAddress, XCOPY_AXI_BUS_A_ADDR_AP_CTRL, Data | 0x01);
}

u32 XCopy_axi_IsDone(XCopy_axi *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCopy_axi_ReadReg(InstancePtr->Bus_a_BaseAddress, XCOPY_AXI_BUS_A_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XCopy_axi_IsIdle(XCopy_axi *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCopy_axi_ReadReg(InstancePtr->Bus_a_BaseAddress, XCOPY_AXI_BUS_A_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XCopy_axi_IsReady(XCopy_axi *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCopy_axi_ReadReg(InstancePtr->Bus_a_BaseAddress, XCOPY_AXI_BUS_A_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XCopy_axi_EnableAutoRestart(XCopy_axi *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCopy_axi_WriteReg(InstancePtr->Bus_a_BaseAddress, XCOPY_AXI_BUS_A_ADDR_AP_CTRL, 0x80);
}

void XCopy_axi_DisableAutoRestart(XCopy_axi *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCopy_axi_WriteReg(InstancePtr->Bus_a_BaseAddress, XCOPY_AXI_BUS_A_ADDR_AP_CTRL, 0);
}

void XCopy_axi_InterruptGlobalEnable(XCopy_axi *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCopy_axi_WriteReg(InstancePtr->Bus_a_BaseAddress, XCOPY_AXI_BUS_A_ADDR_GIE, 1);
}

void XCopy_axi_InterruptGlobalDisable(XCopy_axi *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCopy_axi_WriteReg(InstancePtr->Bus_a_BaseAddress, XCOPY_AXI_BUS_A_ADDR_GIE, 0);
}

void XCopy_axi_InterruptEnable(XCopy_axi *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCopy_axi_ReadReg(InstancePtr->Bus_a_BaseAddress, XCOPY_AXI_BUS_A_ADDR_IER);
    XCopy_axi_WriteReg(InstancePtr->Bus_a_BaseAddress, XCOPY_AXI_BUS_A_ADDR_IER, Register | Mask);
}

void XCopy_axi_InterruptDisable(XCopy_axi *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCopy_axi_ReadReg(InstancePtr->Bus_a_BaseAddress, XCOPY_AXI_BUS_A_ADDR_IER);
    XCopy_axi_WriteReg(InstancePtr->Bus_a_BaseAddress, XCOPY_AXI_BUS_A_ADDR_IER, Register & (~Mask));
}

void XCopy_axi_InterruptClear(XCopy_axi *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCopy_axi_WriteReg(InstancePtr->Bus_a_BaseAddress, XCOPY_AXI_BUS_A_ADDR_ISR, Mask);
}

u32 XCopy_axi_InterruptGetEnabled(XCopy_axi *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCopy_axi_ReadReg(InstancePtr->Bus_a_BaseAddress, XCOPY_AXI_BUS_A_ADDR_IER);
}

u32 XCopy_axi_InterruptGetStatus(XCopy_axi *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCopy_axi_ReadReg(InstancePtr->Bus_a_BaseAddress, XCOPY_AXI_BUS_A_ADDR_ISR);
}

