// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xroundtrip.h"

extern XRoundtrip_Config XRoundtrip_ConfigTable[];

XRoundtrip_Config *XRoundtrip_LookupConfig(u16 DeviceId) {
	XRoundtrip_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XROUNDTRIP_NUM_INSTANCES; Index++) {
		if (XRoundtrip_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XRoundtrip_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XRoundtrip_Initialize(XRoundtrip *InstancePtr, u16 DeviceId) {
	XRoundtrip_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XRoundtrip_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XRoundtrip_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

