// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xcopy_axi.h"

extern XCopy_axi_Config XCopy_axi_ConfigTable[];

XCopy_axi_Config *XCopy_axi_LookupConfig(u16 DeviceId) {
	XCopy_axi_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCOPY_AXI_NUM_INSTANCES; Index++) {
		if (XCopy_axi_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XCopy_axi_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XCopy_axi_Initialize(XCopy_axi *InstancePtr, u16 DeviceId) {
	XCopy_axi_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XCopy_axi_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XCopy_axi_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

