// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XGEMM_H
#define XGEMM_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xgemm_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Bus_a_BaseAddress;
} XGemm_Config;
#endif

typedef struct {
    u32 Bus_a_BaseAddress;
    u32 IsReady;
} XGemm;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XGemm_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XGemm_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XGemm_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XGemm_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XGemm_Initialize(XGemm *InstancePtr, u16 DeviceId);
XGemm_Config* XGemm_LookupConfig(u16 DeviceId);
int XGemm_CfgInitialize(XGemm *InstancePtr, XGemm_Config *ConfigPtr);
#else
int XGemm_Initialize(XGemm *InstancePtr, const char* InstanceName);
int XGemm_Release(XGemm *InstancePtr);
#endif

void XGemm_Start(XGemm *InstancePtr);
u32 XGemm_IsDone(XGemm *InstancePtr);
u32 XGemm_IsIdle(XGemm *InstancePtr);
u32 XGemm_IsReady(XGemm *InstancePtr);
void XGemm_EnableAutoRestart(XGemm *InstancePtr);
void XGemm_DisableAutoRestart(XGemm *InstancePtr);

u32 XGemm_Get_m1_0_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_0_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_0_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m1_0_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m1_0_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m1_0_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m1_0_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m1_0_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m1_0_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m1_1_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_1_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_1_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m1_1_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m1_1_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m1_1_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m1_1_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m1_1_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m1_1_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m1_2_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_2_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_2_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m1_2_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m1_2_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m1_2_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m1_2_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m1_2_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m1_2_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m1_3_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_3_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_3_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m1_3_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m1_3_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m1_3_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m1_3_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m1_3_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m1_3_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m1_4_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_4_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_4_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m1_4_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m1_4_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m1_4_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m1_4_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m1_4_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m1_4_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m1_5_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_5_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_5_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m1_5_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m1_5_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m1_5_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m1_5_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m1_5_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m1_5_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m1_6_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_6_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_6_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m1_6_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m1_6_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m1_6_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m1_6_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m1_6_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m1_6_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m1_7_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_7_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_7_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m1_7_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m1_7_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m1_7_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m1_7_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m1_7_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m1_7_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m1_8_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_8_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_8_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m1_8_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m1_8_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m1_8_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m1_8_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m1_8_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m1_8_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m1_9_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_9_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_9_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m1_9_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m1_9_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m1_9_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m1_9_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m1_9_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m1_9_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m1_10_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_10_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_10_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m1_10_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m1_10_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m1_10_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m1_10_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m1_10_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m1_10_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m1_11_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_11_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_11_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m1_11_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m1_11_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m1_11_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m1_11_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m1_11_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m1_11_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m1_12_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_12_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_12_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m1_12_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m1_12_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m1_12_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m1_12_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m1_12_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m1_12_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m1_13_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_13_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_13_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m1_13_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m1_13_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m1_13_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m1_13_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m1_13_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m1_13_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m1_14_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_14_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_14_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m1_14_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m1_14_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m1_14_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m1_14_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m1_14_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m1_14_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m1_15_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_15_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m1_15_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m1_15_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m1_15_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m1_15_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m1_15_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m1_15_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m1_15_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m2_0_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_0_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_0_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m2_0_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m2_0_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m2_0_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m2_0_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m2_0_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m2_0_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m2_1_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_1_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_1_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m2_1_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m2_1_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m2_1_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m2_1_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m2_1_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m2_1_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m2_2_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_2_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_2_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m2_2_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m2_2_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m2_2_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m2_2_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m2_2_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m2_2_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m2_3_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_3_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_3_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m2_3_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m2_3_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m2_3_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m2_3_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m2_3_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m2_3_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m2_4_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_4_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_4_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m2_4_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m2_4_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m2_4_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m2_4_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m2_4_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m2_4_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m2_5_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_5_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_5_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m2_5_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m2_5_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m2_5_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m2_5_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m2_5_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m2_5_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m2_6_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_6_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_6_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m2_6_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m2_6_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m2_6_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m2_6_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m2_6_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m2_6_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m2_7_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_7_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_7_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m2_7_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m2_7_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m2_7_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m2_7_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m2_7_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m2_7_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m2_8_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_8_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_8_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m2_8_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m2_8_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m2_8_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m2_8_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m2_8_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m2_8_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m2_9_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_9_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_9_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m2_9_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m2_9_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m2_9_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m2_9_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m2_9_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m2_9_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m2_10_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_10_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_10_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m2_10_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m2_10_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m2_10_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m2_10_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m2_10_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m2_10_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m2_11_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_11_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_11_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m2_11_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m2_11_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m2_11_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m2_11_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m2_11_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m2_11_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m2_12_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_12_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_12_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m2_12_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m2_12_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m2_12_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m2_12_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m2_12_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m2_12_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m2_13_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_13_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_13_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m2_13_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m2_13_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m2_13_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m2_13_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m2_13_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m2_13_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m2_14_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_14_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_14_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m2_14_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m2_14_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m2_14_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m2_14_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m2_14_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m2_14_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_m2_15_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_15_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_m2_15_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_m2_15_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_m2_15_Depth(XGemm *InstancePtr);
u32 XGemm_Write_m2_15_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_m2_15_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_m2_15_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_m2_15_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_prod_0_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_0_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_0_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_prod_0_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_prod_0_Depth(XGemm *InstancePtr);
u32 XGemm_Write_prod_0_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_prod_0_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_prod_0_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_prod_0_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_prod_1_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_1_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_1_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_prod_1_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_prod_1_Depth(XGemm *InstancePtr);
u32 XGemm_Write_prod_1_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_prod_1_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_prod_1_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_prod_1_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_prod_2_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_2_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_2_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_prod_2_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_prod_2_Depth(XGemm *InstancePtr);
u32 XGemm_Write_prod_2_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_prod_2_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_prod_2_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_prod_2_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_prod_3_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_3_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_3_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_prod_3_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_prod_3_Depth(XGemm *InstancePtr);
u32 XGemm_Write_prod_3_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_prod_3_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_prod_3_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_prod_3_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_prod_4_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_4_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_4_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_prod_4_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_prod_4_Depth(XGemm *InstancePtr);
u32 XGemm_Write_prod_4_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_prod_4_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_prod_4_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_prod_4_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_prod_5_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_5_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_5_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_prod_5_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_prod_5_Depth(XGemm *InstancePtr);
u32 XGemm_Write_prod_5_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_prod_5_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_prod_5_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_prod_5_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_prod_6_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_6_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_6_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_prod_6_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_prod_6_Depth(XGemm *InstancePtr);
u32 XGemm_Write_prod_6_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_prod_6_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_prod_6_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_prod_6_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_prod_7_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_7_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_7_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_prod_7_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_prod_7_Depth(XGemm *InstancePtr);
u32 XGemm_Write_prod_7_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_prod_7_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_prod_7_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_prod_7_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_prod_8_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_8_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_8_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_prod_8_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_prod_8_Depth(XGemm *InstancePtr);
u32 XGemm_Write_prod_8_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_prod_8_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_prod_8_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_prod_8_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_prod_9_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_9_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_9_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_prod_9_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_prod_9_Depth(XGemm *InstancePtr);
u32 XGemm_Write_prod_9_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_prod_9_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_prod_9_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_prod_9_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_prod_10_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_10_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_10_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_prod_10_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_prod_10_Depth(XGemm *InstancePtr);
u32 XGemm_Write_prod_10_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_prod_10_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_prod_10_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_prod_10_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_prod_11_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_11_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_11_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_prod_11_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_prod_11_Depth(XGemm *InstancePtr);
u32 XGemm_Write_prod_11_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_prod_11_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_prod_11_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_prod_11_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_prod_12_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_12_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_12_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_prod_12_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_prod_12_Depth(XGemm *InstancePtr);
u32 XGemm_Write_prod_12_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_prod_12_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_prod_12_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_prod_12_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_prod_13_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_13_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_13_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_prod_13_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_prod_13_Depth(XGemm *InstancePtr);
u32 XGemm_Write_prod_13_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_prod_13_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_prod_13_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_prod_13_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_prod_14_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_14_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_14_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_prod_14_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_prod_14_Depth(XGemm *InstancePtr);
u32 XGemm_Write_prod_14_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_prod_14_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_prod_14_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_prod_14_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Get_prod_15_BaseAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_15_HighAddress(XGemm *InstancePtr);
u32 XGemm_Get_prod_15_TotalBytes(XGemm *InstancePtr);
u32 XGemm_Get_prod_15_BitWidth(XGemm *InstancePtr);
u32 XGemm_Get_prod_15_Depth(XGemm *InstancePtr);
u32 XGemm_Write_prod_15_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Read_prod_15_Words(XGemm *InstancePtr, int offset, int *data, int length);
u32 XGemm_Write_prod_15_Bytes(XGemm *InstancePtr, int offset, char *data, int length);
u32 XGemm_Read_prod_15_Bytes(XGemm *InstancePtr, int offset, char *data, int length);

void XGemm_InterruptGlobalEnable(XGemm *InstancePtr);
void XGemm_InterruptGlobalDisable(XGemm *InstancePtr);
void XGemm_InterruptEnable(XGemm *InstancePtr, u32 Mask);
void XGemm_InterruptDisable(XGemm *InstancePtr, u32 Mask);
void XGemm_InterruptClear(XGemm *InstancePtr, u32 Mask);
u32 XGemm_InterruptGetEnabled(XGemm *InstancePtr);
u32 XGemm_InterruptGetStatus(XGemm *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
