// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XMERGESORT_H
#define XMERGESORT_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmergesort_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Bus_a_BaseAddress;
} XMergesort_Config;
#endif

typedef struct {
    u32 Bus_a_BaseAddress;
    u32 IsReady;
} XMergesort;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMergesort_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMergesort_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMergesort_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMergesort_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMergesort_Initialize(XMergesort *InstancePtr, u16 DeviceId);
XMergesort_Config* XMergesort_LookupConfig(u16 DeviceId);
int XMergesort_CfgInitialize(XMergesort *InstancePtr, XMergesort_Config *ConfigPtr);
#else
int XMergesort_Initialize(XMergesort *InstancePtr, const char* InstanceName);
int XMergesort_Release(XMergesort *InstancePtr);
#endif

void XMergesort_Start(XMergesort *InstancePtr);
u32 XMergesort_IsDone(XMergesort *InstancePtr);
u32 XMergesort_IsIdle(XMergesort *InstancePtr);
u32 XMergesort_IsReady(XMergesort *InstancePtr);
void XMergesort_EnableAutoRestart(XMergesort *InstancePtr);
void XMergesort_DisableAutoRestart(XMergesort *InstancePtr);


void XMergesort_InterruptGlobalEnable(XMergesort *InstancePtr);
void XMergesort_InterruptGlobalDisable(XMergesort *InstancePtr);
void XMergesort_InterruptEnable(XMergesort *InstancePtr, u32 Mask);
void XMergesort_InterruptDisable(XMergesort *InstancePtr, u32 Mask);
void XMergesort_InterruptClear(XMergesort *InstancePtr, u32 Mask);
u32 XMergesort_InterruptGetEnabled(XMergesort *InstancePtr);
u32 XMergesort_InterruptGetStatus(XMergesort *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
