// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xspmv.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSpmv_CfgInitialize(XSpmv *InstancePtr, XSpmv_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_a_BaseAddress = ConfigPtr->Bus_a_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSpmv_Start(XSpmv *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSpmv_ReadReg(InstancePtr->Bus_a_BaseAddress, XSPMV_BUS_A_ADDR_AP_CTRL) & 0x80;
    XSpmv_WriteReg(InstancePtr->Bus_a_BaseAddress, XSPMV_BUS_A_ADDR_AP_CTRL, Data | 0x01);
}

u32 XSpmv_IsDone(XSpmv *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSpmv_ReadReg(InstancePtr->Bus_a_BaseAddress, XSPMV_BUS_A_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XSpmv_IsIdle(XSpmv *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSpmv_ReadReg(InstancePtr->Bus_a_BaseAddress, XSPMV_BUS_A_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XSpmv_IsReady(XSpmv *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSpmv_ReadReg(InstancePtr->Bus_a_BaseAddress, XSPMV_BUS_A_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XSpmv_EnableAutoRestart(XSpmv *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSpmv_WriteReg(InstancePtr->Bus_a_BaseAddress, XSPMV_BUS_A_ADDR_AP_CTRL, 0x80);
}

void XSpmv_DisableAutoRestart(XSpmv *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSpmv_WriteReg(InstancePtr->Bus_a_BaseAddress, XSPMV_BUS_A_ADDR_AP_CTRL, 0);
}

void XSpmv_InterruptGlobalEnable(XSpmv *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSpmv_WriteReg(InstancePtr->Bus_a_BaseAddress, XSPMV_BUS_A_ADDR_GIE, 1);
}

void XSpmv_InterruptGlobalDisable(XSpmv *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSpmv_WriteReg(InstancePtr->Bus_a_BaseAddress, XSPMV_BUS_A_ADDR_GIE, 0);
}

void XSpmv_InterruptEnable(XSpmv *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSpmv_ReadReg(InstancePtr->Bus_a_BaseAddress, XSPMV_BUS_A_ADDR_IER);
    XSpmv_WriteReg(InstancePtr->Bus_a_BaseAddress, XSPMV_BUS_A_ADDR_IER, Register | Mask);
}

void XSpmv_InterruptDisable(XSpmv *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSpmv_ReadReg(InstancePtr->Bus_a_BaseAddress, XSPMV_BUS_A_ADDR_IER);
    XSpmv_WriteReg(InstancePtr->Bus_a_BaseAddress, XSPMV_BUS_A_ADDR_IER, Register & (~Mask));
}

void XSpmv_InterruptClear(XSpmv *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSpmv_WriteReg(InstancePtr->Bus_a_BaseAddress, XSPMV_BUS_A_ADDR_ISR, Mask);
}

u32 XSpmv_InterruptGetEnabled(XSpmv *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSpmv_ReadReg(InstancePtr->Bus_a_BaseAddress, XSPMV_BUS_A_ADDR_IER);
}

u32 XSpmv_InterruptGetStatus(XSpmv *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSpmv_ReadReg(InstancePtr->Bus_a_BaseAddress, XSPMV_BUS_A_ADDR_ISR);
}

