// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// BUS_A
// 0x00000 : Control signals
//           bit 0  - ap_start (Read/Write/COH)
//           bit 1  - ap_done (Read/COR)
//           bit 2  - ap_idle (Read)
//           bit 3  - ap_ready (Read)
//           bit 7  - auto_restart (Read/Write)
//           others - reserved
// 0x00004 : Global Interrupt Enable Register
//           bit 0  - Global Interrupt Enable (Read/Write)
//           others - reserved
// 0x00008 : IP Interrupt Enable Register (Read/Write)
//           bit 0  - Channel 0 (ap_done)
//           bit 1  - Channel 1 (ap_ready)
//           others - reserved
// 0x0000c : IP Interrupt Status Register (Read/TOW)
//           bit 0  - Channel 0 (ap_done)
//           bit 1  - Channel 1 (ap_ready)
//           others - reserved
// 0x04000 ~
// 0x07fff : Memory 'm1_0' (4096 * 32b)
//           Word n : bit [31:0] - m1_0[n]
// 0x08000 ~
// 0x0bfff : Memory 'm1_1' (4096 * 32b)
//           Word n : bit [31:0] - m1_1[n]
// 0x0c000 ~
// 0x0ffff : Memory 'm1_2' (4096 * 32b)
//           Word n : bit [31:0] - m1_2[n]
// 0x10000 ~
// 0x13fff : Memory 'm1_3' (4096 * 32b)
//           Word n : bit [31:0] - m1_3[n]
// 0x14000 ~
// 0x17fff : Memory 'm1_4' (4096 * 32b)
//           Word n : bit [31:0] - m1_4[n]
// 0x18000 ~
// 0x1bfff : Memory 'm1_5' (4096 * 32b)
//           Word n : bit [31:0] - m1_5[n]
// 0x1c000 ~
// 0x1ffff : Memory 'm1_6' (4096 * 32b)
//           Word n : bit [31:0] - m1_6[n]
// 0x20000 ~
// 0x23fff : Memory 'm1_7' (4096 * 32b)
//           Word n : bit [31:0] - m1_7[n]
// 0x24000 ~
// 0x27fff : Memory 'm1_8' (4096 * 32b)
//           Word n : bit [31:0] - m1_8[n]
// 0x28000 ~
// 0x2bfff : Memory 'm1_9' (4096 * 32b)
//           Word n : bit [31:0] - m1_9[n]
// 0x2c000 ~
// 0x2ffff : Memory 'm1_10' (4096 * 32b)
//           Word n : bit [31:0] - m1_10[n]
// 0x30000 ~
// 0x33fff : Memory 'm1_11' (4096 * 32b)
//           Word n : bit [31:0] - m1_11[n]
// 0x34000 ~
// 0x37fff : Memory 'm1_12' (4096 * 32b)
//           Word n : bit [31:0] - m1_12[n]
// 0x38000 ~
// 0x3bfff : Memory 'm1_13' (4096 * 32b)
//           Word n : bit [31:0] - m1_13[n]
// 0x3c000 ~
// 0x3ffff : Memory 'm1_14' (4096 * 32b)
//           Word n : bit [31:0] - m1_14[n]
// 0x40000 ~
// 0x43fff : Memory 'm1_15' (4096 * 32b)
//           Word n : bit [31:0] - m1_15[n]
// 0x44000 ~
// 0x47fff : Memory 'm2_0' (4096 * 32b)
//           Word n : bit [31:0] - m2_0[n]
// 0x48000 ~
// 0x4bfff : Memory 'm2_1' (4096 * 32b)
//           Word n : bit [31:0] - m2_1[n]
// 0x4c000 ~
// 0x4ffff : Memory 'm2_2' (4096 * 32b)
//           Word n : bit [31:0] - m2_2[n]
// 0x50000 ~
// 0x53fff : Memory 'm2_3' (4096 * 32b)
//           Word n : bit [31:0] - m2_3[n]
// 0x54000 ~
// 0x57fff : Memory 'm2_4' (4096 * 32b)
//           Word n : bit [31:0] - m2_4[n]
// 0x58000 ~
// 0x5bfff : Memory 'm2_5' (4096 * 32b)
//           Word n : bit [31:0] - m2_5[n]
// 0x5c000 ~
// 0x5ffff : Memory 'm2_6' (4096 * 32b)
//           Word n : bit [31:0] - m2_6[n]
// 0x60000 ~
// 0x63fff : Memory 'm2_7' (4096 * 32b)
//           Word n : bit [31:0] - m2_7[n]
// 0x64000 ~
// 0x67fff : Memory 'm2_8' (4096 * 32b)
//           Word n : bit [31:0] - m2_8[n]
// 0x68000 ~
// 0x6bfff : Memory 'm2_9' (4096 * 32b)
//           Word n : bit [31:0] - m2_9[n]
// 0x6c000 ~
// 0x6ffff : Memory 'm2_10' (4096 * 32b)
//           Word n : bit [31:0] - m2_10[n]
// 0x70000 ~
// 0x73fff : Memory 'm2_11' (4096 * 32b)
//           Word n : bit [31:0] - m2_11[n]
// 0x74000 ~
// 0x77fff : Memory 'm2_12' (4096 * 32b)
//           Word n : bit [31:0] - m2_12[n]
// 0x78000 ~
// 0x7bfff : Memory 'm2_13' (4096 * 32b)
//           Word n : bit [31:0] - m2_13[n]
// 0x7c000 ~
// 0x7ffff : Memory 'm2_14' (4096 * 32b)
//           Word n : bit [31:0] - m2_14[n]
// 0x80000 ~
// 0x83fff : Memory 'm2_15' (4096 * 32b)
//           Word n : bit [31:0] - m2_15[n]
// 0x84000 ~
// 0x87fff : Memory 'prod_0' (4096 * 32b)
//           Word n : bit [31:0] - prod_0[n]
// 0x88000 ~
// 0x8bfff : Memory 'prod_1' (4096 * 32b)
//           Word n : bit [31:0] - prod_1[n]
// 0x8c000 ~
// 0x8ffff : Memory 'prod_2' (4096 * 32b)
//           Word n : bit [31:0] - prod_2[n]
// 0x90000 ~
// 0x93fff : Memory 'prod_3' (4096 * 32b)
//           Word n : bit [31:0] - prod_3[n]
// 0x94000 ~
// 0x97fff : Memory 'prod_4' (4096 * 32b)
//           Word n : bit [31:0] - prod_4[n]
// 0x98000 ~
// 0x9bfff : Memory 'prod_5' (4096 * 32b)
//           Word n : bit [31:0] - prod_5[n]
// 0x9c000 ~
// 0x9ffff : Memory 'prod_6' (4096 * 32b)
//           Word n : bit [31:0] - prod_6[n]
// 0xa0000 ~
// 0xa3fff : Memory 'prod_7' (4096 * 32b)
//           Word n : bit [31:0] - prod_7[n]
// 0xa4000 ~
// 0xa7fff : Memory 'prod_8' (4096 * 32b)
//           Word n : bit [31:0] - prod_8[n]
// 0xa8000 ~
// 0xabfff : Memory 'prod_9' (4096 * 32b)
//           Word n : bit [31:0] - prod_9[n]
// 0xac000 ~
// 0xaffff : Memory 'prod_10' (4096 * 32b)
//           Word n : bit [31:0] - prod_10[n]
// 0xb0000 ~
// 0xb3fff : Memory 'prod_11' (4096 * 32b)
//           Word n : bit [31:0] - prod_11[n]
// 0xb4000 ~
// 0xb7fff : Memory 'prod_12' (4096 * 32b)
//           Word n : bit [31:0] - prod_12[n]
// 0xb8000 ~
// 0xbbfff : Memory 'prod_13' (4096 * 32b)
//           Word n : bit [31:0] - prod_13[n]
// 0xbc000 ~
// 0xbffff : Memory 'prod_14' (4096 * 32b)
//           Word n : bit [31:0] - prod_14[n]
// 0xc0000 ~
// 0xc3fff : Memory 'prod_15' (4096 * 32b)
//           Word n : bit [31:0] - prod_15[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XGEMM_BUS_A_ADDR_AP_CTRL      0x00000
#define XGEMM_BUS_A_ADDR_GIE          0x00004
#define XGEMM_BUS_A_ADDR_IER          0x00008
#define XGEMM_BUS_A_ADDR_ISR          0x0000c
#define XGEMM_BUS_A_ADDR_M1_0_BASE    0x04000
#define XGEMM_BUS_A_ADDR_M1_0_HIGH    0x07fff
#define XGEMM_BUS_A_WIDTH_M1_0        32
#define XGEMM_BUS_A_DEPTH_M1_0        4096
#define XGEMM_BUS_A_ADDR_M1_1_BASE    0x08000
#define XGEMM_BUS_A_ADDR_M1_1_HIGH    0x0bfff
#define XGEMM_BUS_A_WIDTH_M1_1        32
#define XGEMM_BUS_A_DEPTH_M1_1        4096
#define XGEMM_BUS_A_ADDR_M1_2_BASE    0x0c000
#define XGEMM_BUS_A_ADDR_M1_2_HIGH    0x0ffff
#define XGEMM_BUS_A_WIDTH_M1_2        32
#define XGEMM_BUS_A_DEPTH_M1_2        4096
#define XGEMM_BUS_A_ADDR_M1_3_BASE    0x10000
#define XGEMM_BUS_A_ADDR_M1_3_HIGH    0x13fff
#define XGEMM_BUS_A_WIDTH_M1_3        32
#define XGEMM_BUS_A_DEPTH_M1_3        4096
#define XGEMM_BUS_A_ADDR_M1_4_BASE    0x14000
#define XGEMM_BUS_A_ADDR_M1_4_HIGH    0x17fff
#define XGEMM_BUS_A_WIDTH_M1_4        32
#define XGEMM_BUS_A_DEPTH_M1_4        4096
#define XGEMM_BUS_A_ADDR_M1_5_BASE    0x18000
#define XGEMM_BUS_A_ADDR_M1_5_HIGH    0x1bfff
#define XGEMM_BUS_A_WIDTH_M1_5        32
#define XGEMM_BUS_A_DEPTH_M1_5        4096
#define XGEMM_BUS_A_ADDR_M1_6_BASE    0x1c000
#define XGEMM_BUS_A_ADDR_M1_6_HIGH    0x1ffff
#define XGEMM_BUS_A_WIDTH_M1_6        32
#define XGEMM_BUS_A_DEPTH_M1_6        4096
#define XGEMM_BUS_A_ADDR_M1_7_BASE    0x20000
#define XGEMM_BUS_A_ADDR_M1_7_HIGH    0x23fff
#define XGEMM_BUS_A_WIDTH_M1_7        32
#define XGEMM_BUS_A_DEPTH_M1_7        4096
#define XGEMM_BUS_A_ADDR_M1_8_BASE    0x24000
#define XGEMM_BUS_A_ADDR_M1_8_HIGH    0x27fff
#define XGEMM_BUS_A_WIDTH_M1_8        32
#define XGEMM_BUS_A_DEPTH_M1_8        4096
#define XGEMM_BUS_A_ADDR_M1_9_BASE    0x28000
#define XGEMM_BUS_A_ADDR_M1_9_HIGH    0x2bfff
#define XGEMM_BUS_A_WIDTH_M1_9        32
#define XGEMM_BUS_A_DEPTH_M1_9        4096
#define XGEMM_BUS_A_ADDR_M1_10_BASE   0x2c000
#define XGEMM_BUS_A_ADDR_M1_10_HIGH   0x2ffff
#define XGEMM_BUS_A_WIDTH_M1_10       32
#define XGEMM_BUS_A_DEPTH_M1_10       4096
#define XGEMM_BUS_A_ADDR_M1_11_BASE   0x30000
#define XGEMM_BUS_A_ADDR_M1_11_HIGH   0x33fff
#define XGEMM_BUS_A_WIDTH_M1_11       32
#define XGEMM_BUS_A_DEPTH_M1_11       4096
#define XGEMM_BUS_A_ADDR_M1_12_BASE   0x34000
#define XGEMM_BUS_A_ADDR_M1_12_HIGH   0x37fff
#define XGEMM_BUS_A_WIDTH_M1_12       32
#define XGEMM_BUS_A_DEPTH_M1_12       4096
#define XGEMM_BUS_A_ADDR_M1_13_BASE   0x38000
#define XGEMM_BUS_A_ADDR_M1_13_HIGH   0x3bfff
#define XGEMM_BUS_A_WIDTH_M1_13       32
#define XGEMM_BUS_A_DEPTH_M1_13       4096
#define XGEMM_BUS_A_ADDR_M1_14_BASE   0x3c000
#define XGEMM_BUS_A_ADDR_M1_14_HIGH   0x3ffff
#define XGEMM_BUS_A_WIDTH_M1_14       32
#define XGEMM_BUS_A_DEPTH_M1_14       4096
#define XGEMM_BUS_A_ADDR_M1_15_BASE   0x40000
#define XGEMM_BUS_A_ADDR_M1_15_HIGH   0x43fff
#define XGEMM_BUS_A_WIDTH_M1_15       32
#define XGEMM_BUS_A_DEPTH_M1_15       4096
#define XGEMM_BUS_A_ADDR_M2_0_BASE    0x44000
#define XGEMM_BUS_A_ADDR_M2_0_HIGH    0x47fff
#define XGEMM_BUS_A_WIDTH_M2_0        32
#define XGEMM_BUS_A_DEPTH_M2_0        4096
#define XGEMM_BUS_A_ADDR_M2_1_BASE    0x48000
#define XGEMM_BUS_A_ADDR_M2_1_HIGH    0x4bfff
#define XGEMM_BUS_A_WIDTH_M2_1        32
#define XGEMM_BUS_A_DEPTH_M2_1        4096
#define XGEMM_BUS_A_ADDR_M2_2_BASE    0x4c000
#define XGEMM_BUS_A_ADDR_M2_2_HIGH    0x4ffff
#define XGEMM_BUS_A_WIDTH_M2_2        32
#define XGEMM_BUS_A_DEPTH_M2_2        4096
#define XGEMM_BUS_A_ADDR_M2_3_BASE    0x50000
#define XGEMM_BUS_A_ADDR_M2_3_HIGH    0x53fff
#define XGEMM_BUS_A_WIDTH_M2_3        32
#define XGEMM_BUS_A_DEPTH_M2_3        4096
#define XGEMM_BUS_A_ADDR_M2_4_BASE    0x54000
#define XGEMM_BUS_A_ADDR_M2_4_HIGH    0x57fff
#define XGEMM_BUS_A_WIDTH_M2_4        32
#define XGEMM_BUS_A_DEPTH_M2_4        4096
#define XGEMM_BUS_A_ADDR_M2_5_BASE    0x58000
#define XGEMM_BUS_A_ADDR_M2_5_HIGH    0x5bfff
#define XGEMM_BUS_A_WIDTH_M2_5        32
#define XGEMM_BUS_A_DEPTH_M2_5        4096
#define XGEMM_BUS_A_ADDR_M2_6_BASE    0x5c000
#define XGEMM_BUS_A_ADDR_M2_6_HIGH    0x5ffff
#define XGEMM_BUS_A_WIDTH_M2_6        32
#define XGEMM_BUS_A_DEPTH_M2_6        4096
#define XGEMM_BUS_A_ADDR_M2_7_BASE    0x60000
#define XGEMM_BUS_A_ADDR_M2_7_HIGH    0x63fff
#define XGEMM_BUS_A_WIDTH_M2_7        32
#define XGEMM_BUS_A_DEPTH_M2_7        4096
#define XGEMM_BUS_A_ADDR_M2_8_BASE    0x64000
#define XGEMM_BUS_A_ADDR_M2_8_HIGH    0x67fff
#define XGEMM_BUS_A_WIDTH_M2_8        32
#define XGEMM_BUS_A_DEPTH_M2_8        4096
#define XGEMM_BUS_A_ADDR_M2_9_BASE    0x68000
#define XGEMM_BUS_A_ADDR_M2_9_HIGH    0x6bfff
#define XGEMM_BUS_A_WIDTH_M2_9        32
#define XGEMM_BUS_A_DEPTH_M2_9        4096
#define XGEMM_BUS_A_ADDR_M2_10_BASE   0x6c000
#define XGEMM_BUS_A_ADDR_M2_10_HIGH   0x6ffff
#define XGEMM_BUS_A_WIDTH_M2_10       32
#define XGEMM_BUS_A_DEPTH_M2_10       4096
#define XGEMM_BUS_A_ADDR_M2_11_BASE   0x70000
#define XGEMM_BUS_A_ADDR_M2_11_HIGH   0x73fff
#define XGEMM_BUS_A_WIDTH_M2_11       32
#define XGEMM_BUS_A_DEPTH_M2_11       4096
#define XGEMM_BUS_A_ADDR_M2_12_BASE   0x74000
#define XGEMM_BUS_A_ADDR_M2_12_HIGH   0x77fff
#define XGEMM_BUS_A_WIDTH_M2_12       32
#define XGEMM_BUS_A_DEPTH_M2_12       4096
#define XGEMM_BUS_A_ADDR_M2_13_BASE   0x78000
#define XGEMM_BUS_A_ADDR_M2_13_HIGH   0x7bfff
#define XGEMM_BUS_A_WIDTH_M2_13       32
#define XGEMM_BUS_A_DEPTH_M2_13       4096
#define XGEMM_BUS_A_ADDR_M2_14_BASE   0x7c000
#define XGEMM_BUS_A_ADDR_M2_14_HIGH   0x7ffff
#define XGEMM_BUS_A_WIDTH_M2_14       32
#define XGEMM_BUS_A_DEPTH_M2_14       4096
#define XGEMM_BUS_A_ADDR_M2_15_BASE   0x80000
#define XGEMM_BUS_A_ADDR_M2_15_HIGH   0x83fff
#define XGEMM_BUS_A_WIDTH_M2_15       32
#define XGEMM_BUS_A_DEPTH_M2_15       4096
#define XGEMM_BUS_A_ADDR_PROD_0_BASE  0x84000
#define XGEMM_BUS_A_ADDR_PROD_0_HIGH  0x87fff
#define XGEMM_BUS_A_WIDTH_PROD_0      32
#define XGEMM_BUS_A_DEPTH_PROD_0      4096
#define XGEMM_BUS_A_ADDR_PROD_1_BASE  0x88000
#define XGEMM_BUS_A_ADDR_PROD_1_HIGH  0x8bfff
#define XGEMM_BUS_A_WIDTH_PROD_1      32
#define XGEMM_BUS_A_DEPTH_PROD_1      4096
#define XGEMM_BUS_A_ADDR_PROD_2_BASE  0x8c000
#define XGEMM_BUS_A_ADDR_PROD_2_HIGH  0x8ffff
#define XGEMM_BUS_A_WIDTH_PROD_2      32
#define XGEMM_BUS_A_DEPTH_PROD_2      4096
#define XGEMM_BUS_A_ADDR_PROD_3_BASE  0x90000
#define XGEMM_BUS_A_ADDR_PROD_3_HIGH  0x93fff
#define XGEMM_BUS_A_WIDTH_PROD_3      32
#define XGEMM_BUS_A_DEPTH_PROD_3      4096
#define XGEMM_BUS_A_ADDR_PROD_4_BASE  0x94000
#define XGEMM_BUS_A_ADDR_PROD_4_HIGH  0x97fff
#define XGEMM_BUS_A_WIDTH_PROD_4      32
#define XGEMM_BUS_A_DEPTH_PROD_4      4096
#define XGEMM_BUS_A_ADDR_PROD_5_BASE  0x98000
#define XGEMM_BUS_A_ADDR_PROD_5_HIGH  0x9bfff
#define XGEMM_BUS_A_WIDTH_PROD_5      32
#define XGEMM_BUS_A_DEPTH_PROD_5      4096
#define XGEMM_BUS_A_ADDR_PROD_6_BASE  0x9c000
#define XGEMM_BUS_A_ADDR_PROD_6_HIGH  0x9ffff
#define XGEMM_BUS_A_WIDTH_PROD_6      32
#define XGEMM_BUS_A_DEPTH_PROD_6      4096
#define XGEMM_BUS_A_ADDR_PROD_7_BASE  0xa0000
#define XGEMM_BUS_A_ADDR_PROD_7_HIGH  0xa3fff
#define XGEMM_BUS_A_WIDTH_PROD_7      32
#define XGEMM_BUS_A_DEPTH_PROD_7      4096
#define XGEMM_BUS_A_ADDR_PROD_8_BASE  0xa4000
#define XGEMM_BUS_A_ADDR_PROD_8_HIGH  0xa7fff
#define XGEMM_BUS_A_WIDTH_PROD_8      32
#define XGEMM_BUS_A_DEPTH_PROD_8      4096
#define XGEMM_BUS_A_ADDR_PROD_9_BASE  0xa8000
#define XGEMM_BUS_A_ADDR_PROD_9_HIGH  0xabfff
#define XGEMM_BUS_A_WIDTH_PROD_9      32
#define XGEMM_BUS_A_DEPTH_PROD_9      4096
#define XGEMM_BUS_A_ADDR_PROD_10_BASE 0xac000
#define XGEMM_BUS_A_ADDR_PROD_10_HIGH 0xaffff
#define XGEMM_BUS_A_WIDTH_PROD_10     32
#define XGEMM_BUS_A_DEPTH_PROD_10     4096
#define XGEMM_BUS_A_ADDR_PROD_11_BASE 0xb0000
#define XGEMM_BUS_A_ADDR_PROD_11_HIGH 0xb3fff
#define XGEMM_BUS_A_WIDTH_PROD_11     32
#define XGEMM_BUS_A_DEPTH_PROD_11     4096
#define XGEMM_BUS_A_ADDR_PROD_12_BASE 0xb4000
#define XGEMM_BUS_A_ADDR_PROD_12_HIGH 0xb7fff
#define XGEMM_BUS_A_WIDTH_PROD_12     32
#define XGEMM_BUS_A_DEPTH_PROD_12     4096
#define XGEMM_BUS_A_ADDR_PROD_13_BASE 0xb8000
#define XGEMM_BUS_A_ADDR_PROD_13_HIGH 0xbbfff
#define XGEMM_BUS_A_WIDTH_PROD_13     32
#define XGEMM_BUS_A_DEPTH_PROD_13     4096
#define XGEMM_BUS_A_ADDR_PROD_14_BASE 0xbc000
#define XGEMM_BUS_A_ADDR_PROD_14_HIGH 0xbffff
#define XGEMM_BUS_A_WIDTH_PROD_14     32
#define XGEMM_BUS_A_DEPTH_PROD_14     4096
#define XGEMM_BUS_A_ADDR_PROD_15_BASE 0xc0000
#define XGEMM_BUS_A_ADDR_PROD_15_HIGH 0xc3fff
#define XGEMM_BUS_A_WIDTH_PROD_15     32
#define XGEMM_BUS_A_DEPTH_PROD_15     4096

