// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xgemm.h"

extern XGemm_Config XGemm_ConfigTable[];

XGemm_Config *XGemm_LookupConfig(u16 DeviceId) {
	XGemm_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XGEMM_NUM_INSTANCES; Index++) {
		if (XGemm_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XGemm_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XGemm_Initialize(XGemm *InstancePtr, u16 DeviceId) {
	XGemm_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XGemm_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XGemm_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

