// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xstencil.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XStencil_CfgInitialize(XStencil *InstancePtr, XStencil_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_a_BaseAddress = ConfigPtr->Bus_a_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XStencil_Start(XStencil *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XStencil_ReadReg(InstancePtr->Bus_a_BaseAddress, XSTENCIL_BUS_A_ADDR_AP_CTRL) & 0x80;
    XStencil_WriteReg(InstancePtr->Bus_a_BaseAddress, XSTENCIL_BUS_A_ADDR_AP_CTRL, Data | 0x01);
}

u32 XStencil_IsDone(XStencil *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XStencil_ReadReg(InstancePtr->Bus_a_BaseAddress, XSTENCIL_BUS_A_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XStencil_IsIdle(XStencil *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XStencil_ReadReg(InstancePtr->Bus_a_BaseAddress, XSTENCIL_BUS_A_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XStencil_IsReady(XStencil *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XStencil_ReadReg(InstancePtr->Bus_a_BaseAddress, XSTENCIL_BUS_A_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XStencil_EnableAutoRestart(XStencil *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStencil_WriteReg(InstancePtr->Bus_a_BaseAddress, XSTENCIL_BUS_A_ADDR_AP_CTRL, 0x80);
}

void XStencil_DisableAutoRestart(XStencil *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStencil_WriteReg(InstancePtr->Bus_a_BaseAddress, XSTENCIL_BUS_A_ADDR_AP_CTRL, 0);
}

void XStencil_InterruptGlobalEnable(XStencil *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStencil_WriteReg(InstancePtr->Bus_a_BaseAddress, XSTENCIL_BUS_A_ADDR_GIE, 1);
}

void XStencil_InterruptGlobalDisable(XStencil *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStencil_WriteReg(InstancePtr->Bus_a_BaseAddress, XSTENCIL_BUS_A_ADDR_GIE, 0);
}

void XStencil_InterruptEnable(XStencil *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XStencil_ReadReg(InstancePtr->Bus_a_BaseAddress, XSTENCIL_BUS_A_ADDR_IER);
    XStencil_WriteReg(InstancePtr->Bus_a_BaseAddress, XSTENCIL_BUS_A_ADDR_IER, Register | Mask);
}

void XStencil_InterruptDisable(XStencil *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XStencil_ReadReg(InstancePtr->Bus_a_BaseAddress, XSTENCIL_BUS_A_ADDR_IER);
    XStencil_WriteReg(InstancePtr->Bus_a_BaseAddress, XSTENCIL_BUS_A_ADDR_IER, Register & (~Mask));
}

void XStencil_InterruptClear(XStencil *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStencil_WriteReg(InstancePtr->Bus_a_BaseAddress, XSTENCIL_BUS_A_ADDR_ISR, Mask);
}

u32 XStencil_InterruptGetEnabled(XStencil *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XStencil_ReadReg(InstancePtr->Bus_a_BaseAddress, XSTENCIL_BUS_A_ADDR_IER);
}

u32 XStencil_InterruptGetStatus(XStencil *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XStencil_ReadReg(InstancePtr->Bus_a_BaseAddress, XSTENCIL_BUS_A_ADDR_ISR);
}

