// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xviterbi.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XViterbi_CfgInitialize(XViterbi *InstancePtr, XViterbi_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_a_BaseAddress = ConfigPtr->Bus_a_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XViterbi_Start(XViterbi *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XViterbi_ReadReg(InstancePtr->Bus_a_BaseAddress, XVITERBI_BUS_A_ADDR_AP_CTRL) & 0x80;
    XViterbi_WriteReg(InstancePtr->Bus_a_BaseAddress, XVITERBI_BUS_A_ADDR_AP_CTRL, Data | 0x01);
}

u32 XViterbi_IsDone(XViterbi *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XViterbi_ReadReg(InstancePtr->Bus_a_BaseAddress, XVITERBI_BUS_A_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XViterbi_IsIdle(XViterbi *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XViterbi_ReadReg(InstancePtr->Bus_a_BaseAddress, XVITERBI_BUS_A_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XViterbi_IsReady(XViterbi *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XViterbi_ReadReg(InstancePtr->Bus_a_BaseAddress, XVITERBI_BUS_A_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XViterbi_EnableAutoRestart(XViterbi *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XViterbi_WriteReg(InstancePtr->Bus_a_BaseAddress, XVITERBI_BUS_A_ADDR_AP_CTRL, 0x80);
}

void XViterbi_DisableAutoRestart(XViterbi *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XViterbi_WriteReg(InstancePtr->Bus_a_BaseAddress, XVITERBI_BUS_A_ADDR_AP_CTRL, 0);
}

u32 XViterbi_Get_return(XViterbi *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XViterbi_ReadReg(InstancePtr->Bus_a_BaseAddress, XVITERBI_BUS_A_ADDR_AP_RETURN);
    return Data;
}
void XViterbi_InterruptGlobalEnable(XViterbi *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XViterbi_WriteReg(InstancePtr->Bus_a_BaseAddress, XVITERBI_BUS_A_ADDR_GIE, 1);
}

void XViterbi_InterruptGlobalDisable(XViterbi *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XViterbi_WriteReg(InstancePtr->Bus_a_BaseAddress, XVITERBI_BUS_A_ADDR_GIE, 0);
}

void XViterbi_InterruptEnable(XViterbi *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XViterbi_ReadReg(InstancePtr->Bus_a_BaseAddress, XVITERBI_BUS_A_ADDR_IER);
    XViterbi_WriteReg(InstancePtr->Bus_a_BaseAddress, XVITERBI_BUS_A_ADDR_IER, Register | Mask);
}

void XViterbi_InterruptDisable(XViterbi *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XViterbi_ReadReg(InstancePtr->Bus_a_BaseAddress, XVITERBI_BUS_A_ADDR_IER);
    XViterbi_WriteReg(InstancePtr->Bus_a_BaseAddress, XVITERBI_BUS_A_ADDR_IER, Register & (~Mask));
}

void XViterbi_InterruptClear(XViterbi *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XViterbi_WriteReg(InstancePtr->Bus_a_BaseAddress, XVITERBI_BUS_A_ADDR_ISR, Mask);
}

u32 XViterbi_InterruptGetEnabled(XViterbi *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XViterbi_ReadReg(InstancePtr->Bus_a_BaseAddress, XVITERBI_BUS_A_ADDR_IER);
}

u32 XViterbi_InterruptGetStatus(XViterbi *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XViterbi_ReadReg(InstancePtr->Bus_a_BaseAddress, XVITERBI_BUS_A_ADDR_ISR);
}

