// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XVITERBI_H
#define XVITERBI_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xviterbi_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Bus_a_BaseAddress;
} XViterbi_Config;
#endif

typedef struct {
    u32 Bus_a_BaseAddress;
    u32 IsReady;
} XViterbi;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XViterbi_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XViterbi_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XViterbi_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XViterbi_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XViterbi_Initialize(XViterbi *InstancePtr, u16 DeviceId);
XViterbi_Config* XViterbi_LookupConfig(u16 DeviceId);
int XViterbi_CfgInitialize(XViterbi *InstancePtr, XViterbi_Config *ConfigPtr);
#else
int XViterbi_Initialize(XViterbi *InstancePtr, const char* InstanceName);
int XViterbi_Release(XViterbi *InstancePtr);
#endif

void XViterbi_Start(XViterbi *InstancePtr);
u32 XViterbi_IsDone(XViterbi *InstancePtr);
u32 XViterbi_IsIdle(XViterbi *InstancePtr);
u32 XViterbi_IsReady(XViterbi *InstancePtr);
void XViterbi_EnableAutoRestart(XViterbi *InstancePtr);
void XViterbi_DisableAutoRestart(XViterbi *InstancePtr);
u32 XViterbi_Get_return(XViterbi *InstancePtr);


void XViterbi_InterruptGlobalEnable(XViterbi *InstancePtr);
void XViterbi_InterruptGlobalDisable(XViterbi *InstancePtr);
void XViterbi_InterruptEnable(XViterbi *InstancePtr, u32 Mask);
void XViterbi_InterruptDisable(XViterbi *InstancePtr, u32 Mask);
void XViterbi_InterruptClear(XViterbi *InstancePtr, u32 Mask);
u32 XViterbi_InterruptGetEnabled(XViterbi *InstancePtr);
u32 XViterbi_InterruptGetStatus(XViterbi *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
