// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xfft_transpose.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XFft_transpose_CfgInitialize(XFft_transpose *InstancePtr, XFft_transpose_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_a_BaseAddress = ConfigPtr->Bus_a_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XFft_transpose_Start(XFft_transpose *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFft_transpose_ReadReg(InstancePtr->Bus_a_BaseAddress, XFFT_TRANSPOSE_BUS_A_ADDR_AP_CTRL) & 0x80;
    XFft_transpose_WriteReg(InstancePtr->Bus_a_BaseAddress, XFFT_TRANSPOSE_BUS_A_ADDR_AP_CTRL, Data | 0x01);
}

u32 XFft_transpose_IsDone(XFft_transpose *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFft_transpose_ReadReg(InstancePtr->Bus_a_BaseAddress, XFFT_TRANSPOSE_BUS_A_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XFft_transpose_IsIdle(XFft_transpose *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFft_transpose_ReadReg(InstancePtr->Bus_a_BaseAddress, XFFT_TRANSPOSE_BUS_A_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XFft_transpose_IsReady(XFft_transpose *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFft_transpose_ReadReg(InstancePtr->Bus_a_BaseAddress, XFFT_TRANSPOSE_BUS_A_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XFft_transpose_EnableAutoRestart(XFft_transpose *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFft_transpose_WriteReg(InstancePtr->Bus_a_BaseAddress, XFFT_TRANSPOSE_BUS_A_ADDR_AP_CTRL, 0x80);
}

void XFft_transpose_DisableAutoRestart(XFft_transpose *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFft_transpose_WriteReg(InstancePtr->Bus_a_BaseAddress, XFFT_TRANSPOSE_BUS_A_ADDR_AP_CTRL, 0);
}

void XFft_transpose_InterruptGlobalEnable(XFft_transpose *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFft_transpose_WriteReg(InstancePtr->Bus_a_BaseAddress, XFFT_TRANSPOSE_BUS_A_ADDR_GIE, 1);
}

void XFft_transpose_InterruptGlobalDisable(XFft_transpose *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFft_transpose_WriteReg(InstancePtr->Bus_a_BaseAddress, XFFT_TRANSPOSE_BUS_A_ADDR_GIE, 0);
}

void XFft_transpose_InterruptEnable(XFft_transpose *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFft_transpose_ReadReg(InstancePtr->Bus_a_BaseAddress, XFFT_TRANSPOSE_BUS_A_ADDR_IER);
    XFft_transpose_WriteReg(InstancePtr->Bus_a_BaseAddress, XFFT_TRANSPOSE_BUS_A_ADDR_IER, Register | Mask);
}

void XFft_transpose_InterruptDisable(XFft_transpose *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFft_transpose_ReadReg(InstancePtr->Bus_a_BaseAddress, XFFT_TRANSPOSE_BUS_A_ADDR_IER);
    XFft_transpose_WriteReg(InstancePtr->Bus_a_BaseAddress, XFFT_TRANSPOSE_BUS_A_ADDR_IER, Register & (~Mask));
}

void XFft_transpose_InterruptClear(XFft_transpose *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFft_transpose_WriteReg(InstancePtr->Bus_a_BaseAddress, XFFT_TRANSPOSE_BUS_A_ADDR_ISR, Mask);
}

u32 XFft_transpose_InterruptGetEnabled(XFft_transpose *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFft_transpose_ReadReg(InstancePtr->Bus_a_BaseAddress, XFFT_TRANSPOSE_BUS_A_ADDR_IER);
}

u32 XFft_transpose_InterruptGetStatus(XFft_transpose *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFft_transpose_ReadReg(InstancePtr->Bus_a_BaseAddress, XFFT_TRANSPOSE_BUS_A_ADDR_ISR);
}

