// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XFFT_TRANSPOSE_H
#define XFFT_TRANSPOSE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xfft_transpose_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Bus_a_BaseAddress;
} XFft_transpose_Config;
#endif

typedef struct {
    u32 Bus_a_BaseAddress;
    u32 IsReady;
} XFft_transpose;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XFft_transpose_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XFft_transpose_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XFft_transpose_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XFft_transpose_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XFft_transpose_Initialize(XFft_transpose *InstancePtr, u16 DeviceId);
XFft_transpose_Config* XFft_transpose_LookupConfig(u16 DeviceId);
int XFft_transpose_CfgInitialize(XFft_transpose *InstancePtr, XFft_transpose_Config *ConfigPtr);
#else
int XFft_transpose_Initialize(XFft_transpose *InstancePtr, const char* InstanceName);
int XFft_transpose_Release(XFft_transpose *InstancePtr);
#endif

void XFft_transpose_Start(XFft_transpose *InstancePtr);
u32 XFft_transpose_IsDone(XFft_transpose *InstancePtr);
u32 XFft_transpose_IsIdle(XFft_transpose *InstancePtr);
u32 XFft_transpose_IsReady(XFft_transpose *InstancePtr);
void XFft_transpose_EnableAutoRestart(XFft_transpose *InstancePtr);
void XFft_transpose_DisableAutoRestart(XFft_transpose *InstancePtr);


void XFft_transpose_InterruptGlobalEnable(XFft_transpose *InstancePtr);
void XFft_transpose_InterruptGlobalDisable(XFft_transpose *InstancePtr);
void XFft_transpose_InterruptEnable(XFft_transpose *InstancePtr, u32 Mask);
void XFft_transpose_InterruptDisable(XFft_transpose *InstancePtr, u32 Mask);
void XFft_transpose_InterruptClear(XFft_transpose *InstancePtr, u32 Mask);
u32 XFft_transpose_InterruptGetEnabled(XFft_transpose *InstancePtr);
u32 XFft_transpose_InterruptGetStatus(XFft_transpose *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
