// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xstencil.h"

extern XStencil_Config XStencil_ConfigTable[];

XStencil_Config *XStencil_LookupConfig(u16 DeviceId) {
	XStencil_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSTENCIL_NUM_INSTANCES; Index++) {
		if (XStencil_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XStencil_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XStencil_Initialize(XStencil *InstancePtr, u16 DeviceId) {
	XStencil_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XStencil_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XStencil_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

