// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xaes.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XAes_CfgInitialize(XAes *InstancePtr, XAes_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_a_BaseAddress = ConfigPtr->Bus_a_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XAes_Start(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Bus_a_BaseAddress, XAES_BUS_A_ADDR_AP_CTRL) & 0x80;
    XAes_WriteReg(InstancePtr->Bus_a_BaseAddress, XAES_BUS_A_ADDR_AP_CTRL, Data | 0x01);
}

u32 XAes_IsDone(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Bus_a_BaseAddress, XAES_BUS_A_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XAes_IsIdle(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Bus_a_BaseAddress, XAES_BUS_A_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XAes_IsReady(XAes *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_ReadReg(InstancePtr->Bus_a_BaseAddress, XAES_BUS_A_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XAes_EnableAutoRestart(XAes *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Bus_a_BaseAddress, XAES_BUS_A_ADDR_AP_CTRL, 0x80);
}

void XAes_DisableAutoRestart(XAes *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Bus_a_BaseAddress, XAES_BUS_A_ADDR_AP_CTRL, 0);
}

void XAes_InterruptGlobalEnable(XAes *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Bus_a_BaseAddress, XAES_BUS_A_ADDR_GIE, 1);
}

void XAes_InterruptGlobalDisable(XAes *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Bus_a_BaseAddress, XAES_BUS_A_ADDR_GIE, 0);
}

void XAes_InterruptEnable(XAes *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAes_ReadReg(InstancePtr->Bus_a_BaseAddress, XAES_BUS_A_ADDR_IER);
    XAes_WriteReg(InstancePtr->Bus_a_BaseAddress, XAES_BUS_A_ADDR_IER, Register | Mask);
}

void XAes_InterruptDisable(XAes *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAes_ReadReg(InstancePtr->Bus_a_BaseAddress, XAES_BUS_A_ADDR_IER);
    XAes_WriteReg(InstancePtr->Bus_a_BaseAddress, XAES_BUS_A_ADDR_IER, Register & (~Mask));
}

void XAes_InterruptClear(XAes *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_WriteReg(InstancePtr->Bus_a_BaseAddress, XAES_BUS_A_ADDR_ISR, Mask);
}

u32 XAes_InterruptGetEnabled(XAes *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAes_ReadReg(InstancePtr->Bus_a_BaseAddress, XAES_BUS_A_ADDR_IER);
}

u32 XAes_InterruptGetStatus(XAes *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAes_ReadReg(InstancePtr->Bus_a_BaseAddress, XAES_BUS_A_ADDR_ISR);
}

